name: GStreamer Build
on:
  push:
    branches:
      - main
permissions:
  contents: read
  packages: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        with:
          context: tools/gstreamer
          file: tools/gstreamer/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/gstreamer:latest
          platforms: linux/amd64,linux/arm64
